SUPABASE_URL = "https://lrmazikqmrjxfvvwmgzc.supabase.co"
SUPABASE_KEY = ""sb_publishable_VVuCU1OW1RpJ343A6nlcKg_J7X98W1Y
ANTHROPIC_API_KEY = "sk-ant-your-key-here"
ADMIN_USERNAME = "simon"
ADMIN_PASSWORD = "simon256#"
